/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminVentasRouteImport } from './routes/admin.ventas'
import { Route as AdminVaquillasRouteImport } from './routes/admin.vaquillas'
import { Route as AdminTorosRouteImport } from './routes/admin.toros'
import { Route as AdminSaludRouteImport } from './routes/admin.salud'
import { Route as AdminReproduccionRouteImport } from './routes/admin.reproduccion'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminInsumosRouteImport } from './routes/admin.insumos'
import { Route as AdminGenealogiaRouteImport } from './routes/admin.genealogia'
import { Route as AdminFinanzasRouteImport } from './routes/admin.finanzas'
import { Route as AdminConsultorRouteImport } from './routes/admin.consultor'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVentasRoute = AdminVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVaquillasRoute = AdminVaquillasRouteImport.update({
  id: '/vaquillas',
  path: '/vaquillas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTorosRoute = AdminTorosRouteImport.update({
  id: '/toros',
  path: '/toros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaludRoute = AdminSaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReproduccionRoute = AdminReproduccionRouteImport.update({
  id: '/reproduccion',
  path: '/reproduccion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsumosRoute = AdminInsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenealogiaRoute = AdminGenealogiaRouteImport.update({
  id: '/genealogia',
  path: '/genealogia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzasRoute = AdminFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultorRoute = AdminConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/testimonios': typeof TestimoniosRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/consultor': typeof AdminConsultorRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/genealogia': typeof AdminGenealogiaRoute
  '/admin/insumos': typeof AdminInsumosRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/reproduccion': typeof AdminReproduccionRoute
  '/admin/salud': typeof AdminSaludRoute
  '/admin/toros': typeof AdminTorosRoute
  '/admin/vaquillas': typeof AdminVaquillasRoute
  '/admin/ventas': typeof AdminVentasRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/testimonios': typeof TestimoniosRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/consultor': typeof AdminConsultorRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/genealogia': typeof AdminGenealogiaRoute
  '/admin/insumos': typeof AdminInsumosRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/reproduccion': typeof AdminReproduccionRoute
  '/admin/salud': typeof AdminSaludRoute
  '/admin/toros': typeof AdminTorosRoute
  '/admin/vaquillas': typeof AdminVaquillasRoute
  '/admin/ventas': typeof AdminVentasRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/testimonios': typeof TestimoniosRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/consultor': typeof AdminConsultorRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/genealogia': typeof AdminGenealogiaRoute
  '/admin/insumos': typeof AdminInsumosRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/reproduccion': typeof AdminReproduccionRoute
  '/admin/salud': typeof AdminSaludRoute
  '/admin/toros': typeof AdminTorosRoute
  '/admin/vaquillas': typeof AdminVaquillasRoute
  '/admin/ventas': typeof AdminVentasRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/testimonios'
    | '/admin/configuracion'
    | '/admin/consultor'
    | '/admin/finanzas'
    | '/admin/genealogia'
    | '/admin/insumos'
    | '/admin/inventario'
    | '/admin/reproduccion'
    | '/admin/salud'
    | '/admin/toros'
    | '/admin/vaquillas'
    | '/admin/ventas'
    | '/admin/whatsapp'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/testimonios'
    | '/admin/configuracion'
    | '/admin/consultor'
    | '/admin/finanzas'
    | '/admin/genealogia'
    | '/admin/insumos'
    | '/admin/inventario'
    | '/admin/reproduccion'
    | '/admin/salud'
    | '/admin/toros'
    | '/admin/vaquillas'
    | '/admin/ventas'
    | '/admin/whatsapp'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/testimonios'
    | '/admin/configuracion'
    | '/admin/consultor'
    | '/admin/finanzas'
    | '/admin/genealogia'
    | '/admin/insumos'
    | '/admin/inventario'
    | '/admin/reproduccion'
    | '/admin/salud'
    | '/admin/toros'
    | '/admin/vaquillas'
    | '/admin/ventas'
    | '/admin/whatsapp'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  ServiciosRoute: typeof ServiciosRoute
  TestimoniosRoute: typeof TestimoniosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ventas': {
      id: '/admin/ventas'
      path: '/ventas'
      fullPath: '/admin/ventas'
      preLoaderRoute: typeof AdminVentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vaquillas': {
      id: '/admin/vaquillas'
      path: '/vaquillas'
      fullPath: '/admin/vaquillas'
      preLoaderRoute: typeof AdminVaquillasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/toros': {
      id: '/admin/toros'
      path: '/toros'
      fullPath: '/admin/toros'
      preLoaderRoute: typeof AdminTorosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salud': {
      id: '/admin/salud'
      path: '/salud'
      fullPath: '/admin/salud'
      preLoaderRoute: typeof AdminSaludRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reproduccion': {
      id: '/admin/reproduccion'
      path: '/reproduccion'
      fullPath: '/admin/reproduccion'
      preLoaderRoute: typeof AdminReproduccionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insumos': {
      id: '/admin/insumos'
      path: '/insumos'
      fullPath: '/admin/insumos'
      preLoaderRoute: typeof AdminInsumosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genealogia': {
      id: '/admin/genealogia'
      path: '/genealogia'
      fullPath: '/admin/genealogia'
      preLoaderRoute: typeof AdminGenealogiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultor': {
      id: '/admin/consultor'
      path: '/consultor'
      fullPath: '/admin/consultor'
      preLoaderRoute: typeof AdminConsultorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminConsultorRoute: typeof AdminConsultorRoute
  AdminFinanzasRoute: typeof AdminFinanzasRoute
  AdminGenealogiaRoute: typeof AdminGenealogiaRoute
  AdminInsumosRoute: typeof AdminInsumosRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminReproduccionRoute: typeof AdminReproduccionRoute
  AdminSaludRoute: typeof AdminSaludRoute
  AdminTorosRoute: typeof AdminTorosRoute
  AdminVaquillasRoute: typeof AdminVaquillasRoute
  AdminVentasRoute: typeof AdminVentasRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminConsultorRoute: AdminConsultorRoute,
  AdminFinanzasRoute: AdminFinanzasRoute,
  AdminGenealogiaRoute: AdminGenealogiaRoute,
  AdminInsumosRoute: AdminInsumosRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminReproduccionRoute: AdminReproduccionRoute,
  AdminSaludRoute: AdminSaludRoute,
  AdminTorosRoute: AdminTorosRoute,
  AdminVaquillasRoute: AdminVaquillasRoute,
  AdminVentasRoute: AdminVentasRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  ServiciosRoute: ServiciosRoute,
  TestimoniosRoute: TestimoniosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
